on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # 6am UTC time ~ midnight in US
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Excavate
      uses: astelmachonak-nydig/GithubActions@cfb407e41ba6309b4b2aa8ce298a9d7a59796660
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCOOP_BRANCH: develop
        SKIP_UPDATED: '1'
